Api/initial data models
cmokbel1/nba-stat_tracker pull request #4
Opened 2022-08-08 21:53 UTC by cmokbel1

server.js updates for input validation. Updated class models.

2022-08-08 23:40 UTC, 1gm requested changes

2022-08-08 23:40 UTC, 1gm commented on backend/rapidapi/players.js
> +        if (player.data.response.length > 0) {
Why is response an array? Can you put a little comment explaining why we pull the zero index? It's not obvious.

2022-08-08 23:40 UTC, 1gm commented on backend/rapidapi/players.js
> +        return { "error": `Player: ${id} Not Found` };
Maybe `player with id XX not found` is a better message? Also the other functions log an error when the code fails but this one doesn't. We should probably also log the error here.

2022-08-08 23:40 UTC, 1gm commented on backend/rapidapi/players.js
> +        console.log(opts);
You should not be logging your opts as this will output the headers and the API key.

2022-08-08 23:40 UTC, 1gm commented on backend/lib/models.js
> +    this.players = [];
Probably worth commenting that this is an array of RosterPlayer

2022-08-08 23:40 UTC, 1gm commented on backend/lib/models.js
> +  addPlayer(player) {
Needs a comment that player is a RosterPlayer

2022-08-08 23:40 UTC, 1gm commented on backend/rapidapi/teams.js
> +        console.log(opts)
As mentioned above, we should not be logging the opts.

2022-08-08 23:40 UTC, 1gm commented on backend/server.js
> +  const data = await rapidapi.teams.getTeamsByConference(req.params.conference);
You should be using `conf` instead of `req.params.conference`

2022-08-08 23:40 UTC, 1gm commented on backend/server.js
> +  for (let i=0; i < data.length; i++) {
Just making a comment here, no need to change: when we discussed the whole 'nbaApi' interface earlier, we would essentially do all these transformations behind that interface. Can discuss more over voice call.

2022-08-08 23:40 UTC, 1gm commented on backend/server.js
>    const season = req.query.season || 2021;
What happens when req.query.season is a boolean? (hint: there's no validation here)

2022-08-08 23:40 UTC, 1gm commented on backend/server.js
>    const season = req.query.season || 2021;
Same comment as above around validation

2022-08-08 23:40 UTC, 1gm commented on backend/server.js
> +  console.log(data);
This probably doesn't need to be logged.

2022-08-08 23:40 UTC, 1gm commented on backend/server.js
> +Home Page - displays teams organized by conference
These notes can probably be removed and moved to an ignored file if you want to keep them.

2022-08-10 00:29 UTC, 1gm requested changes

2022-08-10 00:29 UTC, 1gm commented on backend/rapidapi/players.js
> +        if (player.data.response.length > 0) {
I see your comment, but what is the difference between player.data.response[0] and player.data.response[1]? Why can this be an array and why are we returning the zero index entry?

2022-08-10 00:29 UTC, 1gm commented on backend/server.js
> +  if (isNaN(req.query.season) && req.query.season.length !== 4) {
This code is buggy: please test your implementations before submitting them for re-review.

2022-08-10 00:29 UTC, 1gm commented on backend/server.js
> +  if (isNaN(req.query.season) && req.query.season.length !== 4) {
This code is buggy: please test your implementations before submitting them for re-review.

2022-08-12 14:42 UTC, cmokbel1 commented on backend/rapidapi/players.js
> +        if (player.data.response.length > 0) {
player.data.response is an array with an object inside of it. so we return the zeroth index because we need to get the jersey data. there is no index 1.

2022-08-12 14:43 UTC, cmokbel1 commented on backend/rapidapi/players.js
> +        if (player.data.response.length > 0) {
zero is the first object item inside the array response so we're returning that

2022-08-12 17:15 UTC, merged